### ISSUE TITLE
Radio

### ISSUE THREAD

**Issue by heeji289** [sipe-team/3-1_sds#5]
## 컴포넌트 기능 정의

- 선택지를 라디오 형태로 보여주고 고를 수 있게 하는 컴포넌트입니다. 한 개의 옵션만 선택할 수 있습니다.
- `RadioGroup`, `Radio`로 Group에 감싸있는 옵션들을 보여주고 사용자 입력을 제어합니다.

## 디자인 요구사항

- 세로 정렬, 가로 정렬 옵션이 있어야 해요

## 컴포넌트 스펙

```javascript
const [value, setValue] = React.useState('option1');

  return (
    <RadioGroup
      value={value}
      onValueChange={(newValue) => setValue(newValue)}
    >
      <Radio value="apple" id="option1">
        사과
      </Radio>

      <Radio value="orange" id="option2">
        오렌지
      </Radio>

      <Radio value="grape" id="option3">
        포도
      </Radio>
    </RadioGroup>
  );
```

## 참고 자료

- [당근 Radio 스펙 문서](https://github.com/daangn/seed-design/blob/82c6fe8f671aa0b88e97e8da655b634eac6f3353/docs/content/component/radio-group/usage.mdx#L2)
- [radix-ui Radio 구현체](https://github.com/radix-ui/primitives/tree/4584a37bfa239c390b516282290cde882dd3af19/packages/react/radio-group)

**Comment by noahluftyang** [comment]
오.. 당근 디자인 시스템은 오픈소스였군요

**Comment by heeji289** [comment]
> 오.. 당근 디자인 시스템은 오픈소스였군요

내부 구현체는 공개되어 있지 않고 스펙 정도만 나와있는 것 같더라구요~
